### ISSUE TITLE
Menu text overlaps with website text on narrower displays

### ISSUE THREAD

**Issue by chendaniely** [cosmicBboy/lander-analytics#25]
on more narrow displays, the buttons on the top overlap with the site text in a weird way, mabe have a few more white pixels under the menubar so there's better separation if people have to scroll

But #18 might solve this

![selection_008](https://cloud.githubusercontent.com/assets/5782147/7348974/c16294e2-ecc3-11e4-915b-f6acd9bb5cfe.png)

**Comment by cosmicBboy** [comment]
screenshot of the whole screen please, it'll be hard to fix this without knowledge what the rest of the screen looks like

**Comment by chendaniely** [comment]
![overlap](https://cloud.githubusercontent.com/assets/5782147/7352817/b4a6c80e-ecdc-11e4-8d16-d06cb259cb5e.png)
