### ISSUE TITLE
New text for About Lander Analytics

### ISSUE THREAD

**Issue by veeps** [cosmicBboy/lander-analytics#29]
Lander Analytics is a New York based data science firm, specializing in statistical programming training and analytic consulting.  We provide services for a wide range of global clients including large corporations, educational facilities, government agencies, sports franchises, small shops and nascent start-ups.

Led by Chief Data Scientist Jared Lander, projects are handled by an elite team of statisticians, data scientists, university professors, visualization designers and management consultants.

We are able to provide cost efficient resources and solutions for a large array of data driven engagements, that can be tailored to your specific requirements and budgets on a per project basis or long term subscription plan.  We are here to help you navigate Big Data and unlock its full potential.

**Comment by cosmicBboy** [comment]
https://docs.google.com/document/d/1xqr_Df30_X1OmWt71TAGkuY4NraTbrvyywdBtNruZ20/edit
