### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by veeps** [cosmicBboy/lander-analytics#34]

**Comment by cosmicBboy** [comment]
relevant stackoverflow question:
http://stackoverflow.com/questions/25354070/meteor-call-function-after-template-is-rendered-with-data

**Comment by cosmicBboy** [comment]
@veeps [I fixed it](http://lander-analytics.meteor.com/)!! It was just a matter of uncommenting the code on the demo:

```
    navigation : true, // Show next and prev buttons
    slideSpeed : 300,
    paginationSpeed : 400,

    // "singleItem:true" is a shortcut for:
    // I uncommented this section
    items : 1, 
    itemsDesktop : false,
    itemsDesktopSmall : false,
    itemsTablet: false,
    itemsMobile : false
```

**Comment by veeps** [comment]
![slide1](https://cloud.githubusercontent.com/assets/5782102/7783932/c145c7fa-0121-11e5-952d-2c11460615ad.jpg)
![slide2](https://cloud.githubusercontent.com/assets/5782102/7783934/c16a5ed0-0121-11e5-8a14-64541d72488b.jpg)
![slide3](https://cloud.githubusercontent.com/assets/5782102/7783933/c16a67a4-0121-11e5-8168-e66a71968108.jpg)

**Comment by veeps** [comment]
In case my commit didn't go through.. at the airport now boarding to London!
