### ISSUE TITLE
Headers change from the main page to other tabs

### ISSUE THREAD

**Issue by chendaniely** [cosmicBboy/lander-analytics#45]
The backgrounds are different and the text shifts a little.  Not sure how much of that you plan/want to be consistent

![selection_011](https://cloud.githubusercontent.com/assets/5782147/7761650/4fdf7e66-fff6-11e4-951b-76070d5c17d7.png)

**Comment by cosmicBboy** [comment]
not relevant anymore. this has been fixed

**Comment by chendaniely** [comment]
is that what #44 was?

**Comment by cosmicBboy** [comment]
no, it was a change that hadn't been pushed up
